### ISSUE TITLE
Twilight Forest Crash (Fabric)

### ISSUE THREAD

**Issue by crowmaticOrb** [ferriarnus/VivecraftForge#100]
Crashes when the Naga or Hydra spawn. The only other mods I had were mouse tweaks, controlling, and sodium but after removing Vivecraft it worked fine. Edit: 1.18.2 Non-VR

**Comment by fayer3** [comment]
someone else had issues with the spike goblin, which I have confirmed.
my current dev version doesn't crash, with that, so once that Is read, I'll post it here for you, so you can check if that also fixes those mobs

**Comment by fayer3** [comment]
should be fixed with 0.0.14, if it persists, please reopen
