### ISSUE TITLE
Possible additional incompatibilities - incompatible with mega12345mega's nbt editor mod.

### ISSUE THREAD

**Issue by TahoeBennie** [ferriarnus/VivecraftForge#113]
The incompatibility is not usage-wise, it ends up crashing upon startup. After having figured things out over at his github, it appears this mod assumes the first element of the title screen is a button. In mega12345mega's nbt editor, it is not anymore, it adds another element so that tabs of another api can be used on any screen. Long story short, it appears that this usage of the title screen elements breaks with certain other mods and can break with others, as it already has broken with one that I use. The error seems to come from [here](https://github.com/ferriarnus/VivecraftMod/blob/d09c2512b91bc0eb747d25a22dbc402c41e0f7e3/common/src/main/java/org/vivecraft/mixin/client/gui/screens/TitleScreenMixin.java#L49).

**Comment by fayer3** [comment]
can you post the error log, if you got one? or is the issue just visual?

**Comment by TahoeBennie** [comment]
The full log upon startup with only the two mods (and fabric api, not sure if it's necesary) is [here](https://mclo.gs/MmjJTzy), sorry i forgot about that. The issue prevents loading the game entirely.

**Comment by fayer3** [comment]
just linking the other issue, to find it again https://github.com/mega12345mega/NBT-Editor/issues/34

**Comment by fayer3** [comment]
added a check, should be fixed in the next version
