### ISSUE TITLE
[1.19.2] The A Button Crashes The Game

### ISSUE THREAD

**Issue by PolyframeX** [ferriarnus/VivecraftForge#116]
When Pressing The A Button, The Game Crashes.

Fabric: 0.14.14
Vivecraft: 0.0.13

Error Log:
[08WTmGZP.txt](https://github.com/ferriarnus/VivecraftMod/files/10772310/08WTmGZP.txt)

Launcher Message:
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7909()" because "i" is null

**Comment by fayer3** [comment]
did you get a crash report? can you post that

**Comment by fayer3** [comment]
it could be the one issue, that is already fixed in the prerelease, full release will come soon

**Comment by PolyframeX** [comment]
I did not get a crash report, the game just freezes then closes.

**Comment by fayer3** [comment]
can you check with that version? 
https://cdn.discordapp.com/attachments/923188682909958185/1073798435095990303/vivecraft-1.19.2-0.0.14-a4-fabric.jar

**Comment by PolyframeX** [comment]
I can't right now, but I will do when I can.

**Comment by fayer3** [comment]
probably fixed with 0.0.14, if not, please reopen
