### ISSUE TITLE
Gui is completely black

### ISSUE THREAD

**Issue by Helinos** [ferriarnus/VivecraftForge#120]
Exactly what it says on the tin.
Using Fabric 0.14.14 with a Quest 2 through ALVR on Linux. Vivecraft is the only mod loaded.

![alvr client quest-20230226-043258](https://user-images.githubusercontent.com/44323833/221392681-984399fa-a9d7-4503-8f71-382ce7f72a48.jpg)
![alvr client quest-20230226-043236](https://user-images.githubusercontent.com/44323833/221392683-692b2284-1d90-4cd7-8d5b-0d2579dd478e.jpg)

**Comment by fayer3** [comment]
log please

**Comment by Helinos** [comment]
https://mclo.gs/GzvMZ8m

**Comment by fayer3** [comment]
can you check without the resourcepack

**Comment by Helinos** [comment]
It was happening before I applied the resource pack, but I double checked anyways.

https://mclo.gs/0Anm4qZ

![2023-02-26_07-35](https://user-images.githubusercontent.com/44323833/221420453-9ade271b-3839-431e-8403-716d5715afe7.png)

**Comment by fayer3** [comment]
weird, I can't reproduce it, does it happen at other locations as well?

**Comment by Helinos** [comment]
What do you mean by other locations?

**Comment by fayer3** [comment]
not at this patch of dirtpath
move around a bit, and check if it goes away
try going to a torch or something

**Comment by Helinos** [comment]
As far as I could tell moving around (Visiting 1000, 1000, flying around the world origin) didn't change anything, nor did going near a torch

**Comment by rwinkhart** [comment]
Same exact issue with OG Vive+Artix Linux. No other mods loaded, happens with both Forge and Fabric.

The old Optifine version of Vivecraft is fine, this only occurs on the new versions without an Optifine dependency.

**Comment by rwinkhart** [comment]
Issue is only present in v0.14+. All versions below v0.14 are fine.

The changelog for v0.14 contains the following:
- changes how the gui/screen is rendered, to be more compatible (fixes Xaeros world map, FancyMenus Fabric)
- fix player gui rendering (e.g.: bedrockify, figura, paperdoll)

**Comment by thejudge156** [comment]
This happens on QCXR as well, I am trying to bump the version but this is preventing progress.

**Comment by thejudge156** [comment]
I can rule out the bedrockify commit however, reverting that did not fix it on my end.

**Comment by thejudge156** [comment]
Also, what might be worth noting is that the main menu is fine. This only occurs ingame.

**Comment by rwinkhart** [comment]
Commit acb23328841aecbb7c1e46e955eb21adfcaffe50 is at fault. I reverted this commit and re-built. Everything is now displaying properly.
