### ISSUE TITLE
Collapse after entering the world

### ISSUE THREAD

**Issue by Dr-WeiAL** [ferriarnus/VivecraftForge#124]
[crash-2023-03-09_03.46.12-client.txt](https://github.com/ferriarnus/VivecraftMod/files/10924830/crash-2023-03-09_03.46.12-client.txt)
The device I use is Rift S. Everything was normal before entering the world, but the game crashed within a few seconds after entering
The game will still crash without installing any other mods

**Comment by fayer3** [comment]
thanks, What language are you playing with?
Am I seeing it correctly, that it is Chinese?

**Comment by Dr-WeiAL** [comment]
Yes, simplified Chinese is used

**Comment by fayer3** [comment]
will fix it for the next version, in the meantime you can temporarily change the language to English, and let the tutorial toasts run through
or open your `options.txt` and set the tutorialstep to none `tutorialStep:none`

**Comment by Dr-WeiAL** [comment]
Ok thank you very much!
