### ISSUE TITLE
Crash on 1.19.4 when pausing (Fabric)

### ISSUE THREAD

**Issue by Ultmate-Mario** [ferriarnus/VivecraftForge#137]
I went on the same mod version for 1.19.3 fabric and it doesn't crash. I haven't tested this on the forge version. Everything seems to work fine including the main menu, but the pause menu just crashes.

Here is my crash log: 
[crash-2023-03-29_09.29.22-client.txt](https://github.com/ferriarnus/VivecraftMod/files/11104689/crash-2023-03-29_09.29.22-client.txt)

**Comment by fayer3** [comment]
issue with modmenu https://github.com/TerraformersMC/ModMenu/issues/582
you can disable the modmenu button for the pause screen, until that is fixed

**Comment by fayer3** [comment]
for people wondering how to disable the mod button on the pause screen:
in the modmenu config file set `modify_game_menu` to `false`

**Comment by fayer3** [comment]
fixed with mod menu 6.2
