### ISSUE TITLE
Java Segfault on arch linux when trying to launch with SteamVR beta

### ISSUE THREAD

**Issue by RedstoneLP2** [ferriarnus/VivecraftForge#140]
Trying to launch Vivecraft 1.19.4-0.0.15 (tried both fabric and forge) with SteamVR 1.26.1 causes Java 17(.0.6+10) to segfault.
Switching to the non-beta version of SteamVR (currently 1.15.7) mitigates the issue.

Versions:
Vivecraft 1.19.4-0.0.15
Java 17.0.6+10
SteamVR beta 1.26.1
ALVR v20.0.0-dev08

Log: https://paste.ee/p/LooG3

**Comment by fayer3** [comment]
probably a steamvr issue, since the error happens in the steamvr library

**Comment by RedstoneLP2** [comment]
Was an issue on my system. I think something managed to break mesa. After an update (which reinstalled the graphics drivers) and reboot it no longer crashes. Sorry for the invalid issue
