### ISSUE TITLE
preview_OptiFine_1.19.2_HD_U_I1_pre4 compatibility

### ISSUE THREAD

**Issue by bomxacalaka** [ferriarnus/VivecraftForge#155]
Vivecraft 1.19.2 needs that specific version of optifine, but AE2 doesnt like that specific version and crashes. Already talked to AE2 community, they say its optifine related, but since vivecraft needs that version(OptiFine_1.19.2_HD_U_H9) I think its easier to get vivecraft to use the latest optifine version(OptiFine_1.19.2_HD_U_I2).

https://pastebin.com/rNVzdpeX

These are the mods used not working:
[appliedenergistics2-forge-12.9.5](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/4548558)
[OptiFine_1.19.2_HD_U_H9](https://optifine.net/adloadx?f=OptiFine_1.19.2_HD_U_I2.jar&x=cb3e)
[vivecraft-1.19.2-jrbudda-VR-2-b8_MOD](https://github.com/jrbudda/Vivecraft_119/releases)
[forge-1.19.2-43.2.0](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.2.html)

extra: AE2 doesnt seem to work with the latest version of optifine but works fine with preview_OptiFine_1.19.2_HD_U_I1_pre4 which I downloaded a while back.

**Comment by fayer3** [comment]
wrong github, you want to go here https://github.com/jrbudda/Vivecraft_119
this github is for the standalone mod version
