### ISSUE TITLE
Reimagined Resource pack glitch

### ISSUE THREAD

**Issue by eightmetal** [ferriarnus/VivecraftForge#160]
When loading into VR with the Reimagined resource pack, the main menu breaks and it is nearly impossible to navigate the menus
![image](https://github.com/ferriarnus/VivecraftMod/assets/78925706/9e7bf1f4-e714-43a9-9ee8-99cc9c315b8f)
I think this may be caused by the way the resource pack alters the background of in game menus
![image](https://github.com/ferriarnus/VivecraftMod/assets/78925706/dec9e944-21a0-41f5-bb77-fef3a8d5e761)
![image](https://github.com/ferriarnus/VivecraftMod/assets/78925706/69dd528f-6dd7-4d29-85de-3d5405b5b549)

**Comment by fayer3** [comment]
even if the cube is rendered wrong, the menu screen should still be the same though, I'll take a look

**Comment by fayer3** [comment]
can you link the pack

**Comment by eightmetal** [comment]
yea np
https://www.curseforge.com/minecraft/texture-packs/minecraft-reimagined

**Comment by fayer3** [comment]
fixed with 1.0.0
