### ISSUE TITLE
Error Code 110

### ISSUE THREAD

**Issue by BraveCaperCat2** [ferriarnus/VivecraftForge#170]
When launching the mod with Essential (allows you to play with your friends without a server, possible mod incompatibility) the mod brings up the error code 110, shown in the image below:
![javaw_Akk0uaofyA](https://github.com/ferriarnus/VivecraftMod/assets/113925022/4d15b188-a11b-404f-82e9-c34ad6593569)
The mod is possibly incompattible with Essential, but it only happens in VR mode, as i've been able to get the mod to launch with essential and more mods in NonVR mode.
Logs and Crash Reports:
[latest.log](https://github.com/ferriarnus/VivecraftMod/files/12251762/latest.log)
[debug.log](https://github.com/ferriarnus/VivecraftMod/files/12251763/debug.log)
no crash report included
SteamVR is installed in steam.
Cannot launch MineCraft as Administrator as it is launched by Curseforge as i am using the CurseForge launcher.
Happens in windows 11
headset was plugged in, although it shouldn't matter.
When launching SteamVR earlier it was saying something about plugging in the headset, although it was already plugged in.
First time using VR, have been able to use Minecraft Bedrock (probably irrelevant) on this computer with the same headset (i only have one)

**Comment by fayer3** [comment]
that error means that it couldn't find steamvr, so maybe try reinstalling it

**Comment by fayer3** [comment]
closing as no response was given

**Comment by BraveCaperCat2** [comment]
i only just installed it that day, the headset was plugged in so steam asked me if i wanted to instal it. sorry for late response.

**Comment by fayer3** [comment]
not sure what you mean with `it asked me`

**Comment by BraveCaperCat2** [comment]
it asked me to install steam vr.

**Comment by fayer3** [comment]
well yeah you need steamvr installed correctly for vivecraft to find it

**Comment by BraveCaperCat2** [comment]
maybe it was that steam and steam vr were installed on a different account to minecraft? i didn't think that would be an issue but now that i think of it yes it might be.
