### ISSUE TITLE
In-world interaction for more blocks

### ISSUE THREAD

**Issue by Zakru** [ferriarnus/VivecraftForge#171]
Tested with a fence gate, I cannot open it by moving my hand in it and clicking. This works with doors, so it seems logical to also be able to open fence gates.

Opening this issue for all blocks in general, I haven't tested others but the fence gate was one of the first things I tried when I found out about this feature. I imagine it would be beneficial to give all interactable blocks a pass, at the very least to decide if they should be interactable or not.

Using Vivecraft 1.19.2-0.0.15-fabric

**Comment by fayer3** [comment]
hm, will check it should only disregard full blocks

**Comment by fayer3** [comment]
okay, the issue is that it's using the wrong collision box, it only triggers on the side posts

**Comment by Zakru** [comment]
Ah, I apologize for the poor wording then! I had the impression that only some blocks were implemented. Glad this got fixed, though.
