### ISSUE TITLE
Strange arm bug after hotswapping.

### ISSUE THREAD

**Issue by crowmaticOrb** [ferriarnus/VivecraftForge#175]
![image](https://github.com/ferriarnus/VivecraftMod/assets/108908589/a2e0363d-ad3c-42a3-addc-5d85824af91c)
this is what other people see

**Comment by fayer3** [comment]
need more details. that player is in VR right?
and I assume the bug report is for the red rectangles?
and what mc version?

**Comment by crowmaticOrb** [comment]
that is me after swapping from vr to non-vr, the red rectangles are a different part of my skin showing up there for some reason.

**Comment by crowmaticOrb** [comment]
the arms should be normal mc arms but they aren't

**Comment by fayer3** [comment]
I need a latest.log and a modlist, if that is on forge, then, some mod must be messing with it

**Comment by crowmaticOrb** [comment]
1.20.1 Fabric,
Modlist:
```
6 Trapdoors
Adorn
Armorful
Axes Are Weapons
CIT Resewn
Chunky
Compress It!
Cosmetic Armor
CraftPresence
Craftify
Enchanting Infuser
Enhanced Workbenches
Extended Drawers
Forge Config API Port
Item Highlighter
Iceberg
Just Enough Professions (JEP)
Just Enough Resources (JER)
Legendary Tooltips
Mouse Tweaks
No Chat Reports
Ping Wheel
Presence Footsteps
Prism
Puzzles Lib
Show Me What You Got
Simple Copper Pipes
Tax Free Levels
Simple Uncrafting Table
Variant Furnaces
Wilder Wild
Xaero's World Map
Xaero's Minimap
Zoomify
AntiGhost
AppleSkin
Architectury API
Areas
Balm
betterfpsdist mod
Carry On
Chat Heads
Cloth Config API
Collective
Connected Glass
Crafting Tweaks
cupboard
DashLoader
Let's Do: API
Double Doors
Dynamic View Mod
Enhanced Block Entities
Entity Culling
Exline's Furniture
Expanded Storage
Extract Poison
Fabric API
Fabric Language Kotlin
Farsight Mod
FastQuit
FerriteCore
Flat Bedrock
Grass Seeds
Universal Graves
Hardcore Revival
Indium
Just Enough Effect Descriptions (JEED)
Just Enough Items
Krypton
LambDynamicLights
LazyDFU
Leather Bundles
Let Me Despawn
Let's Do: Vinery
Lithium
Logprot
lootbeams
Lootr
FastAnim
Make Bubbles Pop
MCPitanLib
Memory Leak Fix
MicroCutting
Mob Captains
Mo' Colors
Model Gap Fix
Modern Glass Doors
ModernFix
Mod Menu
Moonlight Lib
More Mob Variants
Move Boats
Move Minecarts
M.R.U
Nether Wart Blocks to Nether Warts
Pack It Up!
Craftable Saddle
Random Village Names
Recast
Shulker Box Tooltip
Simple Hats
6 Stairs
Smoothchunk mod
Sodium
Spawn Animations
Starlight (Fabric)
SuperMartijn642's Core Lib
Supplementaries
Tom's Simple Storage Mod
Tree Harvester
Trinkets
Valhelsia Core
Valhelsia Furniture
Voice Chat Interaction
View Distance Fix
Villager Names
Vivecraft
Simple Voice Chat
Weaker Spiderwebs
Wolves Of Other Furs (W.O.O.F)
YetAnotherConfigLib
```
[latest.log](https://github.com/Vivecraft/VivecraftMod/files/12326233/latest.log)

**Comment by fayer3** [comment]
hm works fine on my end with those mods, only one I couldn't find is `telltale_heart` that is mentioned in your log

**Comment by fayer3** [comment]
is this consistent for other players?

**Comment by crowmaticOrb** [comment]
i tested again and it seems to be consistent for other players, this only occurs for other people after i switch from vr to non-vr without restarting the game

**Comment by crowmaticOrb** [comment]
head and arm positions for other players seem dependent on their positions when you switch modes

**Comment by crowmaticOrb** [comment]
when i leave their render distance and come back, the issue seems to go away

**Comment by fayer3** [comment]
weird, that either means the switch network packet isn't sent from your client, or the server doesn't forward it. do you have any other mods on the server, besides those?

**Comment by fayer3** [comment]
and could you send a server log, can also dm it on discord

**Comment by crowmaticOrb** [comment]
[latest.log](https://github.com/Vivecraft/VivecraftMod/files/12330254/latest.4.log)
the mods on client and server are the same

**Comment by fayer3** [comment]
not seeing any issues, and can't reproduce it here. would you be willing to run a special version, that would log the VR active packets on the server and client, to see if those work as expected?

**Comment by crowmaticOrb** [comment]
yes i can do that dm it on discord

**Comment by fayer3** [comment]
here, test with that, and send me a client and server log
need to unzip it, github doesn't let me attach jars
[vivecraft-1.20.1-1.0.1-vractive_logging-fabric.jar.zip](https://github.com/Vivecraft/VivecraftMod/files/12340254/vivecraft-1.20.1-1.0.1-vractive_logging-fabric.jar.zip)

**Comment by fayer3** [comment]
oh, didn't see the dm on discord, I'll send it there too

**Comment by crowmaticOrb** [comment]
im also sending my friends log in case that would help
[server.log](https://github.com/Vivecraft/VivecraftMod/files/12340540/server.log)
[my client.log](https://github.com/Vivecraft/VivecraftMod/files/12340541/my.client.log)
[friend client.log](https://github.com/Vivecraft/VivecraftMod/files/12340542/friend.client.log)

**Comment by fayer3** [comment]
hm, and you hotswitched from VR to NONVR there? I don't even see a switch attempt

**Comment by crowmaticOrb** [comment]
yes, i played in vr for a bit, then switched from vr to nonvr, then closed steamvr

**Comment by fayer3** [comment]
hm, I don't see any switching, just 2 server connects. the game successfully switched to nonvr for you?

**Comment by crowmaticOrb** [comment]
yes, all the vr stuff was disabled, and i was able to close steamvr without it closing minecraft

**Comment by fayer3** [comment]
hm wait, maybe I missunderstood, what exactly did you do,
did you enter the server in VR, left it, turned VR off, and rejoined?

**Comment by fayer3** [comment]
> yes, all the vr stuff was disabled, and i was able to close steamvr without it closing minecraft

because that shouldn't work, when hotswitching without leaving the server. for steamvr to not close the game, VR needs to be disabled in the main menu

**Comment by crowmaticOrb** [comment]
no, i left, then switched to nonvr, then joined back and this issue happened

**Comment by fayer3** [comment]
ah, okay, then this is only a server issue probably, I thought you hotswitched when in the game

**Comment by fayer3** [comment]
will look at that tomorrow

**Comment by fayer3** [comment]
if this is still an issue with the test version I sent you let me know
