### ISSUE TITLE
V-sync Toggle

### ISSUE THREAD

**Issue by keanine** [ferriarnus/VivecraftForge#179]
I'm running the Fabric 1.20.1-1.0.1 version of Vivecraft.

I've noticed something interesting with my headset. When I set it to 72Hz I get 72FPS without shaders and 36FPS with shaders. When I set my headset to 90Hz I get 90FPS without shaders and 45FPS with shaders. My guess is that Vivecraft forces v-sync on to avoid tearing, so in my case with shaders on I can't quite reach 72FPS or 90FPS, so the target goes down to half. 

To solve this I would love to try disabling V-Sync but the option in-game is already off. I assume vivecraft must have its own method of V-Sync that is inaccessible, so having access to a toggle for this feature would be really useful if possible.

**Comment by fayer3** [comment]
can't do, vsync is controlled by steamvr and the headset driver, and there is no way to disable it afaik
some headsets are more lenient, when disabling motion smoothing, like my Vve doesn't force 45, unless I enable motion smoothing
