### ISSUE TITLE
Cannot compile Immersive Portals branch

### ISSUE THREAD

**Issue by Dunk0w0** [ferriarnus/VivecraftForge#182]
I mentioned it in #89 but I figured it could use it's own issue tracker (if not feel free to close this!)
Basically the gradle just doesn't work for the [Immersive Portals branch](https://github.com/ferriarnus/VivecraftMod.git), as the Maven repositories seem to be wrong. I believe [this ](https://github.com/ferriarnus/VivecraftMod/commit/f83099a62a5f6c49bf7c6a135a836198682f5013)was the issue and was fixed on the main mod, but was never fixed for this. Unfortunately I don't know enough to fix it myself so the help would be very appreciated!

[log.txt](https://github.com/ferriarnus/VivecraftMod/files/12460634/log.txt) (Error that is given when trying to compile the mod)

**Comment by fayer3** [comment]
the immersive portals branch is oudated, no plan to fix that atm, I'm just working on a new one.

**Comment by Dunk0w0** [comment]
@fayer3 Is there any way I can donate to you? I appreciate what you're doing and I know it's a lot of work, and since I don't have the coding experience to actually help, is there any way I could give you some money instead?

**Comment by fayer3** [comment]
we now have a Ko-fi page, if you want to donate https://ko-fi.com/vivecraft
