### ISSUE TITLE
Intel Arc support

### ISSUE THREAD

**Issue by Pleune** [ferriarnus/VivecraftForge#195]
Intel arc is working well for me in Windows Mixed Reality, but vivecraft does not support Arc. Do the same limitations of the intel integrated graphics drivers apply to Arc? Or, is there a possibility of Arc support in the future?

**Comment by fayer3** [comment]
same limitations apply, it's a driver side issue. 
there is PR #194 , which changes it to a windows only block, and allows it on linux, since there are no issues there
