### ISSUE TITLE
Extreme Tracking Lag - Linux

### ISSUE THREAD

**Issue by ghost** [ferriarnus/VivecraftForge#197]
Hi, I'm using linux and there's extreme tracking lag, making the game unplayable. Using the 1.19.2 version of the regular vivecraft (the one that has an installer) works fine, with none of the tracking lag. I'm on Nvidia, have have tried using prism launcher alongside the regular launcher. The forge version that isn't the installer also has the same issue.

**Comment by fayer3** [comment]
any mods? and can you post a latest.log

**Comment by fayer3** [comment]
no response, closing
