### ISSUE TITLE
When hot switch to VR mod Game Crashed on Debian Linux Bookworm

### ISSUE THREAD

**Issue by ShulkerSakura** [ferriarnus/VivecraftForge#234]
GPU: RTX3060 6G laptop
Driver: 525.125.06
Java: Graalvm JDK 17.0.4
VRHMD: Valve Index
Game Version : 1.20.4
Mod: fabric-0.15.3,fabric-api-0.92.0,modmenu-9.0.0-pre1,vivecraft-1.20.4-1.1.6
Status: When put on the hmd to switch to VR mod the game freezes and crash in few secnod.
Crash Log:
[hs_err_pid19667.log](https://github.com/Vivecraft/VivecraftMod/files/13801525/hs_err_pid19667.log)

**Comment by fayer3** [comment]
removed the access token from the log file for you

**Comment by fayer3** [comment]
and this is on linux I assume, right?

**Comment by ShulkerSakura** [comment]
> 为您从日志文件中删除访问令牌

Thank you so much,And yes it is on Linux

**Comment by fayer3** [comment]
can you check that your steamvr install is okay, bvecause that seems to crash

**Comment by ShulkerSakura** [comment]
> can you check that your steamvr install is okay, bvecause that seems to crash

SteamVR is run properly, test in SteamVRHome & VRChat

**Comment by fayer3** [comment]
and steams file integrity check didn't show any errors?

**Comment by ShulkerSakura** [comment]
> and steams file integrity check didn't show any errors?

No any error

**Comment by fayer3** [comment]
does this issue still happen with latest steam and steamvr?

**Comment by fayer3** [comment]
closing since no response
