### ISSUE TITLE
Pokecube Compatibility

### ISSUE THREAD

**Issue by DarianLStephens** [ferriarnus/VivecraftForge#241]
Pokecube, 1.20.1, 1-3.24.0.i
https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi

I'm not sure you need the log for this, but I'll do it if asked. I'd generate one now, but I'm really tired and about to go to bed, to the point where I can't be bothered to get the VR stuff going right now.

**Issue Description:**
I don't know if this is on your side or Pokecube's side, but the core feature of the mod, the Pokecubes, don't work.

The titular 'Pokecube' item, filled or not, cannot be used. It cannot be thrown, holding the right-click button just leads to your right arm pulling back and forth like it's _trying_ to throw, but nothing happens.
It's also attached to your left hand, and huge, for whatever reason. Switching to third-person item transforms changes nothing that I noticed.

To reproduce, install Pokecube AIO and Vivecraft, then simply hold a Pokecube and try to use it.

**Screenshots:**
![2024-02-04_08 48 51](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/assets/15375876/ce81e565-66ed-4988-973a-2201d53ae20a)
![2024-02-04_08 48 56](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/assets/15375876/0de9e2c4-f5ae-46f7-92c3-9c52d7ef9bb8)

Going back to non-VR, everything works as intended:
![2024-02-04_08 56 07](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/assets/15375876/8717ec1f-6691-4b8b-905c-60c2ce60cab0)
![2024-02-04_08 56 11](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/assets/15375876/f2e9fba5-50fd-475d-bcbe-01681131be0b)

**Comment by fayer3** [comment]
it's probably a bow item, so you need to change
 options > vr settings > interaction settings > roomscale bow
 to vanilla only

**Comment by DarianLStephens** [comment]
If that ends up being the problem, is there a way to configure that setting per-item?

**Comment by fayer3** [comment]
not right now, but I can add a datapack tag for items to exclude

**Comment by DarianLStephens** [comment]
Okay, that worked!
The items are still slightly misplaced and mis-scaled in the hand, even with third person transforms, but it's functional!

**Comment by fayer3** [comment]
how far off is the scale?

**Comment by DarianLStephens** [comment]
This far:
![2024-02-06_23 13 39](https://github.com/Vivecraft/VivecraftMod/assets/15375876/aa57182e-5022-4a8b-ba9a-04646366f40b)

Here's my held Pokecube next to a Pokecube in-world:
![2024-02-06_23 15 02](https://github.com/Vivecraft/VivecraftMod/assets/15375876/fa70472b-7c91-4749-b68a-e15952aa06e6)
I can't quite tell if the placement is also off when it clips in to my hand, or if that's just because of the scale.

**Comment by fayer3** [comment]
you forget that that hand model is as big as a block

**Comment by fayer3** [comment]
at least it looks like that in the first post screenshots

**Comment by DarianLStephens** [comment]
Nah, I was flying.
The hand model itself appears unaffected.

**Comment by fayer3** [comment]
I mean the vanilla screenshots

**Comment by DarianLStephens** [comment]
It's not _obviously_ that big, at least.
It may be scaled inappropriately in the model, just looking right from the fixed first-person perspective. I,E further away than it should be and big, so it still looks normal-sized.
