### ISSUE TITLE
Incompatibility with Embeddium

### ISSUE THREAD

**Issue by Daldwin** [ferriarnus/VivecraftForge#243]
Game crashes on launch when using Embeddium 0.3.1 and Vivecraft 1.1.5 on Minecraft 1.20.1 with Forge 47.2.0 

[crash-2024-02-06_13.32.07-client.txt](https://github.com/Vivecraft/VivecraftMod/files/14183400/crash-2024-02-06_13.32.07-client.txt)
[debug.log](https://github.com/Vivecraft/VivecraftMod/files/14183401/debug.log)
[latest.log](https://github.com/Vivecraft/VivecraftMod/files/14183402/latest.log)

**Comment by fayer3** [comment]
yeah, issue with sodium 0.5.5, didn't think they would backport it, but they did

**Comment by fayer3** [comment]
fixed with 1.1.7, now available
