### ISSUE TITLE
Crash when using Sodium 0.5.8

### ISSUE THREAD

**Issue by MarijnIsN00B** [ferriarnus/VivecraftForge#247]
My game is crashing every time I enter a world using Sodium 0.5.8 and Vivecraft 1.1.5 on Fabric 1.20.1
Crash log: https://mclo.gs/zWCQnp2
I assume this is because 1.1.6 isn't backported to 1.20.1?

**Comment by fayer3** [comment]
yes, the compat stuff isn't backported yet. duplicate of #243

**Comment by DarianLStephens** [comment]
What's the recommended version to use in the meantime, then?

**Comment by fayer3** [comment]
0.5.3

**Comment by Rainee4563** [comment]
took a look over at [#198](https://github.com/embeddedt/embeddium/issues/198) seems like its the blame game

**Comment by fayer3** [comment]
fixed with 1.1.7, now available
