### ISSUE TITLE
Option to decrease brightness below 0?

### ISSUE THREAD

**Issue by kevina** [ferriarnus/VivecraftForge#251]
Vivecraft for 1.16 had the ability to decrease the brightness (gamma) below 0.  That option was lost, I guess when Vivecraft no longer was a modification of OptiFine.

I miss that option, as for me, especially with the original HTC Vive OLED displays everything looked so much better.  I also like the fact that in pitch black I really couldn't see.  Normally even if the brightness set to 0, you could still see somewhat.  For example, box yourself in, give it a second for your eyes to adjust, and you can likely still see the blocks.  For the full effect you might need to make sure there is no light bleed from the room.

For now I found a mod that does so (https://modrinth.com/mod/gamma-utils), but it is awkward to use.  It would be nice if the option acted as an override and as only active when you are in VR.  With the previously mentioned mod,  I always need to increase it back up when not in VR, because it is just too dark for my monitor.

**Comment by fayer3** [comment]
oh, didn't know that was missing, will look

**Comment by kevina** [comment]
In 1.16 the normal brightness slider had the ability to go below 0, I think it was to -50 and labeled as "I Can't See", but I could be mistaken at the exact levels it want down to.

**Comment by fayer3** [comment]
yeah, didn't know we forgot to port that

**Comment by kevina** [comment]
Thanks, it it even possible to modify the brightness slider and have it work with sodium?  I figured that is why the ability to do so got lost.

**Comment by fayer3** [comment]
we just need to modify sodium aswell

**Comment by kevina** [comment]
Okay.  I was thinking a separate option would be better as it can act as an override to only take effect when in VR.  But if you can modify the brightness slider that will work also.

**Comment by fayer3** [comment]
so the 1.18 version didn't have that, either forgotten, or on purpose, and that is why we don't have it, because we built off of that version

**Comment by fayer3** [comment]
closing this, as it's not really needed, since we are a mod now, and people can just install that gamma mod, if they want to lower the brightness.

**Comment by Techjar** [comment]
Yeah you can replicate the same functionality with this mod: https://modrinth.com/mod/gamma-utils

**Comment by fayer3** [comment]
they already linked that mod

**Comment by Techjar** [comment]
Oh I didn't see lol
