### ISSUE TITLE
Why is the latest release marked as incompatible with Sodium on modrinth?

### ISSUE THREAD

**Issue by kevina** [ferriarnus/VivecraftForge#259]
https://modrinth.com/mod/vivecraft/version/1.20.4-1.1.8-fabric

![screenshot](https://github.com/Vivecraft/VivecraftMod/assets/1271492/9de1fa94-08cc-4853-9944-70c12cd83eea)

**Comment by fayer3** [comment]
I marked 0.4.11 as incomoatible, must have taken that as general incompatibility somehow

**Comment by fayer3** [comment]
will remove it manually

**Comment by fayer3** [comment]
fixed
