### ISSUE TITLE
Crash with certian mods

### ISSUE THREAD

**Issue by ghost** [ferriarnus/VivecraftForge#26]
first of all this is 1.18.2 so i don't know if I'm using the version that its meant for but.

these are the mods I'm using

https://pastebin.com/eV3a5rBC

and this is the crash log

https://pastebin.com/F5ApqVRP

it is probably the create mod or immersive portals because those have been known to mess with rendering a lot but i cant be sure as i don't know how to code in java.

**Comment by ferriarnus** [comment]
Yes it seems there are a few conflicts, with create and immersive portals being somewhat known. The actual crash in this case is `port_lib`, which is used by create, but immersive portals doesn't work either. These mods do indeed mess with a lot of rendering, so we will need to carefully integrate with them. The log also mentions some other potential issue, but these 2 would be the main ones. We will definitely look into getting them to be compatible in the future, but for now, unfortunately, they are not.
