### ISSUE TITLE
Vivecraft items appear in Everycompat's creative tab

### ISSUE THREAD

**Issue by rafaelkai** [ferriarnus/VivecraftForge#262]
As the title says:
![2024-03-02_23 41 38](https://github.com/Vivecraft/VivecraftMod/assets/72790002/5a5b15f9-bb80-4acd-8148-256ce009e003)

**Comment by fayer3** [comment]
hm

**Comment by fayer3** [comment]
this one? https://www.curseforge.com/minecraft/mc-mods/every-compat

**Comment by rafaelkai** [comment]
Yes, exactly that mod

**Comment by fayer3** [comment]
any specific mc version?

**Comment by rafaelkai** [comment]
Using latest Vivecraft and Everycompat versions for 1.20.1

**Comment by fayer3** [comment]
can you give me a list of mods you used to get that, I have a bit of trouble to get that mod to do anything

**Comment by fayer3** [comment]
hm, okay so the issues is that the tab is a search tab, and we add the items to all searches, when the query matches our items

**Comment by Techjar** [comment]
Yeah, we're adding items to the creative menu in a weird non-standard way, since they aren't actually separate items in the registry, just existing items with special NBT data.
