### ISSUE TITLE
make invalid path error more clear how to fix

### ISSUE THREAD

**Issue by Diamondminer1Y** [ferriarnus/VivecraftForge#263]
when i try to launch fear nightfall modpack and click to enable the vr features of the mod it shows up this error(look screenshot) also im not in any steam vr beta i have tried clean reinstallation of minecraft the only problem is when i try to play in vr mode
![Screenshot 2024-03-12 151211](https://github.com/Vivecraft/VivecraftMod/assets/163143014/6ae15997-0db3-4f67-9251-3c68106d7686)

**Comment by fayer3** [comment]
that means you need to move the game directory out of the user folder.
steamvr doesn't like special characters in the path. I probably should make that error more descriptive

**Comment by fayer3** [comment]
fixed with 983d868a9500b23367616f674d2434c613fa2e23
the error now includes a line of how to fix it
