### ISSUE TITLE
Compatability with Iris + DH

### ISSUE THREAD

**Issue by Halowigeds** [ferriarnus/VivecraftForge#266]
AFAIK they are not compatible yet

**Comment by fayer3** [comment]
the curretn github state should load with both, maybe will look wrong though, the current realease doesn't work

**Comment by Halowigeds** [comment]
Are there plans to officially support it?

**Comment by fayer3** [comment]
yeah

**Comment by fayer3** [comment]
should already work in the releases, just for got to close this. most DH compatible shaders just don't work out of the box with Vivecraft yet
