### ISSUE TITLE
little tiles conflict

### ISSUE THREAD

**Issue by fayer3** [ferriarnus/VivecraftForge#268]
these two mixins are conflicting
https://github.com/CreativeMD/LittleTiles/blob/bf2278ea20472e7fc44b2b1fe8ea7f37fb39d7ae/src/main/java/team/creative/littletiles/mixin/client/MinecraftMixin.java#L89-L92

https://github.com/Vivecraft/VivecraftMod/blob/aa05773834fad7c47eaf01612287bfde18d7065f/common/src/main/java/org/vivecraft/mixin/client_vr/MinecraftVRMixin.java#L569-L572

```
littletiles.mixins.json:client.MinecraftMixin from mod littletiles->@Redirect::isDestroying(Lnet/minecraft/client/multiplayer/MultiPlayerGameMode;)Z with priority 1000, already redirected by vivecraft.mixins.json:client_vr.MinecraftVRMixin from mod vivecraft->@Redirect::vivecraft$seatedCheck(Lnet/minecraft/client/multiplayer/MultiPlayerGameMode;)Z with priority 1000 
```

**Comment by ferriarnus** [comment]
Guess we can use something like wrap operation from mixin extra's to fix the conflict? I think we both would need to.

**Comment by fayer3** [comment]
a wrap should at least not crash I think

**Comment by fayer3** [comment]
if we also wrap after them, I think it should wrap the redirect

**Comment by Techjar** [comment]
What does this mixin actually do?

**Comment by fayer3** [comment]
seems to cancel the startUseItem in non seated mode

**Comment by fayer3** [comment]
sorry, read it backwards, if that returns true the method is canceled, but we seem to want to run it always in standing mode

**Comment by CreativeMD** [comment]
Made use of MixinExtra's wrapper operator, which should hopefully fix this issue.

**Comment by fayer3** [comment]
duplicate of #278 I somhow logged this twice
