### ISSUE TITLE
I can't to start VR mode

### ISSUE THREAD

**Issue by bmd070** [ferriarnus/VivecraftForge#272]
I have problem with a file "action_manifest.json" in the folder "openvr". I play on the 1.20.1 fabric but 1.19.2 forge and 1.20.1 forge also doesn't work. For more information I'll present a png file:
![Screenshot 2024-04-24 165613](https://github.com/Vivecraft/VivecraftMod/assets/132436585/1ee858d5-3900-4515-80bb-b3a7de5f9b2f)

**Comment by fayer3** [comment]
1. you have to move your game directory out of your user folder to fix that
2. we don't provide support for tlauncher

**Comment by bmd070** [comment]
Thank you everything works
