### ISSUE TITLE
VR Init Error Render setup failed (Linux)

### ISSUE THREAD

**Issue by 2-3-5-41** [ferriarnus/VivecraftForge#275]
# Error

```
VR Init Error
Render setup failed: Installation path could not be located (110)
VR provider: OpenVR_LWJGL
```

# Environment

- os: Arch Linux
- launcher: prism (flatpak)
- Steam & SteamVR installed and running before launching minecraft
- OpenXR & OpenVR system libs installed through pacman
- Exposed `~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64` to prism launcher through flatseal

**Comment by fayer3** [comment]
don't use flatpacks, they cause issues with steamvr

**Comment by Techjar** [comment]
To be more verbose, flatpak overrides a bunch of system paths to create an effective sandbox for libraries and such. It's a clunky workaround to the issue of mismatched system library versions. There's probably a way to expose or symlink the right things, but it'll be far easier to simply install Prism from the AUR instead (https://aur.archlinux.org/packages/prismlauncher).
