### ISSUE TITLE
1.21 Fabric Prevents server from fulling exiting 

### ISSUE THREAD

**Issue by MissPotato** [ferriarnus/VivecraftForge#283]
If a player joins the server and leaves, and then the server is shut down, the server does not finish exiting. It will successfully save chunks, but never actually quit idling forever. 

Vivecraft version vivecraft-1.21-1.1.9-a1-fabric
Fabric version fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1

**Comment by fayer3** [comment]
not having any issue here

**Comment by fayer3** [comment]
any other mods? and what mode is the joined player in, or does that not matter. and are there other players on the server , or just the one

**Comment by MissPotato** [comment]
I will have to do more testing. It was just myself joining the server to test a datapack, and when I went to turn off the server it wouldn't finish shutting off. I was also in survival mode, but that doesn't seem to matter as I think I was also in creative mode at one point.

**Comment by MissPotato** [comment]
It happens with only vivecraft. I disabled all other mods. 

More info about the enviroment:
OpenJDK version 21.0.3
OpenJDK Runtime 21.0.3.9-ubuntu
Ubuntu 23~22.04.1-Ubuntu 
Running on the oracle cloud using a Ampere A1 VM, I believe it is a Altra Arm cpu


EDIT: Might also be relevant but the client is a Manjaro Linux, running on the same JDK version, with an intel CPU, connecting as vanilla (no vive mod or fabric loader.)

**Comment by fayer3** [comment]
and you are stopping the server withthe `stop` command?

**Comment by fayer3** [comment]
and yare you runmning the default vivecraft server config, or did you make any changes

**Comment by MissPotato** [comment]
Yes, I'm closing the server with the stop command, and no, all configs including server.properties are default (except the world seed)

**Comment by hammy275** [comment]
I've had the same issue here for a while. I couldn't give a timeframe on "a while", since it never occurred to me that it might be a Vivecraft issue. I always thought it was a non-vanilla server issue that just happens sometimes. That said, thinking on it, I _think_ all the servers I experience this issue with are ones with the Vivecraft mod installed.

I sadly cannot recall if this happens under Forge, but I can say that it happens with Minecraft versions well before 1.21 (I know with certainty it happens under 1.20.1).

Just in case I'm accidentally talking about a different issue, the symptoms of this are that, on server shutdown, all saving goes fine (all dimensions save, etc.), but the server process itself doesn't exit.

**Comment by MissPotato** [comment]
Yeah, that's the same issue.

**Comment by fayer3** [comment]
hm

**Comment by fayer3** [comment]
@MissPotato could you try this one, this disables the message ferature completely, which might be the cause of the issue
[vivecraft-1.21-1.1.9-a1-nomessages-fabric.jar.zip](https://github.com/user-attachments/files/15859129/vivecraft-1.21-1.1.9-a1-nomessages-fabric.jar.zip)

**Comment by MissPotato** [comment]
That seems to have fixed it, I tried a few times and it closed successfully each time.

**Comment by fayer3** [comment]
hm, ned to check why that isn't shutting down correctly t hen

**Comment by MissPotato** [comment]
Considering I'm able to reproduce it every single time, if you wanna provide a verbose version I could provide a log with more debug info.

**Comment by fayer3** [comment]
this should fix it, if you could make sure
[vivecraft-1.21-1.1.9-a1-shutdownexecutor-fabric.jar.zip](https://github.com/user-attachments/files/15859924/vivecraft-1.21-1.1.9-a1-shutdownexecutor-fabric.jar.zip)

**Comment by MissPotato** [comment]
I tried about 5 times with no issues, that seems to have fixed it!
