### ISSUE TITLE
Visual Artifacts with Iris Shaders and Distant Horizons

### ISSUE THREAD

**Issue by StaringLongingly** [ferriarnus/VivecraftForge#285]
Seems like a problem with the rendering order, also only happens when using Shaders
Steps to reproduce:
1. Download Vivecraft, Distant Horizons, Iris
2. Download and enable Complimentary Shaders
3. Visual bug

**Comment by fayer3** [comment]
can you screenshot that, they should work fine

**Comment by StaringLongingly** [comment]
![Screenshot_VirtualDesktop Android_2024 06 30-18 48 45 509_484](https://github.com/Vivecraft/VivecraftMod/assets/74494805/c818e15b-6f0c-4683-87f1-bee6305c868e)
![Screenshot_VirtualDesktop Android_2024 06 30-18 48 50 455_330](https://github.com/Vivecraft/VivecraftMod/assets/74494805/169e528e-e8a4-4a4a-9b51-f0f02c45873e)
![Screenshot_VirtualDesktop Android_2024 06 30-18 48 57 243_031](https://github.com/Vivecraft/VivecraftMod/assets/74494805/8435bb53-cb8c-4c26-b838-186ca9e49d99)

Game version is 1.21 btw

**Comment by fayer3** [comment]
try manually reloading the shaders with `R`

**Comment by StaringLongingly** [comment]
That was it, have a great rest of your day!
