### ISSUE TITLE
Vivecraft overrides custom spyglass models even when VR is disabled.

### ISSUE THREAD

**Issue by FabianMPunkt** [ferriarnus/VivecraftForge#286]
I have a texture pack that changes the handmodel of the Spyglass (https://github.com/FabianMPunkt/Nautilus3D)
Vivecraft replaces this with the default handmodel even when not in VR mode. I can understand that Vivecraft automatically falls back to the default spyglass model due to the added functionality in VR, but it would be nice if it didn't override the spyglass model when not in VR.
Spyglass displays correctly when Vivecraft is not installed.

![image](https://github.com/Vivecraft/VivecraftMod/assets/78741736/6cf31ea5-0865-40c8-aee7-7b18902498b0)

![image](https://github.com/Vivecraft/VivecraftMod/assets/78741736/5fb023fd-6722-4e52-860e-cfe6772a128d)

![image](https://github.com/Vivecraft/VivecraftMod/assets/78741736/257be238-bd43-4871-8e46-f4d37d1e6424)

**Comment by fayer3** [comment]
thanks for reporting, I'll check it out
