### ISSUE TITLE
game crashed with embeddium on 1.21

### ISSUE THREAD

**Issue by Fury94-Echo** [ferriarnus/VivecraftForge#292]
[crash-2024-08-12_10.13.56-client.txt](https://github.com/user-attachments/files/16581417/crash-2024-08-12_10.13.56-client.txt)

**Comment by ferriarnus** [comment]
Hmm, potential mixin conflict?

**Comment by fayer3** [comment]
this is such a stupid micro optimization from them https://github.com/embeddedt/embeddium/blob/21.0/neoforge/src/main/java/org/embeddedt/embeddium/impl/mixin/features/shader/uniform/ShaderProgramMixin.java#L80-L93

**Comment by fayer3** [comment]
even changing that to a mixin extras mixin, will not fix it, because the it will crash with an array out of bounds exeption

**Comment by fayer3** [comment]
I guess if we make sure we are after them it will just run twice

**Comment by ferriarnus** [comment]
They need to change it to use an accessor, not depending on it being 12 I think. I'll talk with them about it. Why was it not 12 again? I faintly recal us changing it, not the why.

**Comment by fayer3** [comment]
we change it, because we add additional samplers to fabulous

**Comment by fayer3** [comment]
should be fixed with embeddium 0.3.29 by https://github.com/embeddedt/embeddium/commit/e910ec46e590a929a5c5cd37e9e3c70b8dc1014e
