### ISSUE TITLE
Sticky piston causing Crash

### ISSUE THREAD

**Issue by SnowiYi** [ferriarnus/VivecraftForge#295]
Hi, i was testing Vivecraft on my freind's survival world, and figured out that sticky piston retracting was crashing the game, I looked into the logs and Vivecraft is procurung this issue because i tried on an instance with only Vivecraft installed

Hope this helped!

**Comment by fayer3** [comment]
could you please also post the log

**Comment by fayer3** [comment]
cannot reproduce I need your log buddy.

**Comment by SnowiYi** [comment]
[crash-2024-08-27_17.05.40-client.txt](https://github.com/user-attachments/files/16782937/crash-2024-08-27_17.05.40-client.txt)

**Comment by SnowiYi** [comment]
Here is the crash report

**Comment by fayer3** [comment]
that is a crash caused by continuity

**Comment by fayer3** [comment]
don't see how that would be in any way caused by us

**Comment by SnowiYi** [comment]
Oh okay, thanks for figuring it out, i am not an expert in log reading

**Comment by fayer3** [comment]
you seem to be missing indium, which is needed when using continuity with sodium(pre 0.6)
