### ISSUE TITLE
New update randomly crashes me

### ISSUE THREAD

**Issue by ImEden6** [ferriarnus/VivecraftForge#297]
[latest.log](https://github.com/user-attachments/files/16956389/latest.log)

**Comment by fayer3** [comment]
hm that log doesn't have a regular crash in it. did it make a `hs_err_pid` log in your base minecraft folder?

**Comment by ImEden6** [comment]
nope, i assume its this mod making me crash since they just updated their hud renderer

**Comment by fayer3** [comment]
well there isn't any crash in the log you posted. did you get a crash report you can post, or any special error exit code?

**Comment by fayer3** [comment]
check if you got an `hs_err_pid` log in you mc folder. of you don't respond I'll close this issue

**Comment by fayer3** [comment]
closing since no response
