### ISSUE TITLE
vr doesn't work

### ISSUE THREAD

**Issue by ruslya678** [ferriarnus/VivecraftForge#301]
Failed to install action manifest
Invalid characters in path: 
C:\Users\§cр§r§cс§r\AppData\Roaming\mimenart\openvr\input\action_manifest.json
#
To fix this error, change your Minecraft game directory to somewhere outside the folder with marked characters.

**Comment by fayer3** [comment]
do what the error says. set your minecraft game directory to something outside your user folder
