### ISSUE TITLE
How do you make a custom main menu world?

### ISSUE THREAD

**Issue by GuyFromTheInternet** [ferriarnus/VivecraftForge#309]
The menu world settings do mention an option to select custom only world, but there appears to be zero documentation on how to create a menu world

**Comment by fayer3** [comment]
- bind the `Export Menu World` key in the mc options
- boot into a world
- look in the direction you want the title screen to face
- press the assigned keybind (game might freeze for a bit, and report in chat if the export was successful)

**Comment by fayer3** [comment]
you can do that in both VR or NONVR
