### ISSUE TITLE
Reset Origin while in seated can be triggered while no VR headset is connected, causing a crash

### ISSUE THREAD

**Issue by Cartrigger** [ferriarnus/VivecraftForge#325]
https://mclo.gs/itu0crb 

If you do a nifty trick by going to VR Settings --> Seated, turning it on, then pressing `reset origin`, it crashes instantly. I would have to guess is because it doesn't actually check if a headset is connected before trying it. This also occurred on 1.20.1, where I originally found it on a modded instance.

Minor bug.

**Comment by fayer3** [comment]
already fixed, just not in a release
