### ISSUE TITLE
Loot tables from other mods don’t work

### ISSUE THREAD

**Issue by MastroCaleb** [ferriarnus/VivecraftForge#34]
Just for testing i was using some mods with vr and every modded block i mined just didn’t drop a single thing (the same for modded entities), the moment i delete vivecraft from the mods folder and play the game normally it works just fine. This is a big issue for anyone who wants to play with mods.

**Comment by ferriarnus** [comment]
Hmm, that's odd. Can you give a log? even if it doesn't crash, it should tell us something.

**Comment by MastroCaleb** [comment]
Sure, give me a minute

**Comment by fayer3** [comment]
maybe related, how terralith fails to load its datapack.

**Comment by ferriarnus** [comment]
I think it is. We are *somehow* stopping the loading of those json's

**Comment by MastroCaleb** [comment]
Found it. After the logs "END VR DEVICE: 1" there is "Missing Data Pack Fabric Mods". In some way you are indeed not letting fabric load any data folder
[latest.log](https://github.com/ferriarnus/VivecraftMod/files/9505512/latest.log)

**Comment by ferriarnus** [comment]
Ok, solved, I'll push the update. Should be available in an hour tops, depending on how fast curseforge is

**Comment by MastroCaleb** [comment]
nice, good job
