### ISSUE TITLE
CC: Restitched Compatibility

### ISSUE THREAD

**Issue by jamac-dumas** [ferriarnus/VivecraftForge#42]
Turtles from [CC: Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched) are causing a crash when Vivecraft is also installed.

I ran into this issue on my Fabric server after adding Vivecraft v0.0.10 while using [CC: Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched) v1.100.8.

To reproduce the issue:
* Install both Vivecraft and CC: Restitched
* Place a melee turtle
* Run the `turtle.attack()` function in Lua on the turtle

[Here is the crash report](https://pastebin.com/8sDPAR6J)

I didn't test it, but I would guess that doing any "player" action with a turtle will cause this crash, since it seems related to the fake player CC: Restitched uses.

**Comment by fayer3** [comment]
can you check, if this

1.  doesn't crash
2. behaves as it should

need to unzip it, github didn't let me  attach a jar
[vivecraft-0.0.10-fabric.zip](https://github.com/ferriarnus/VivecraftMod/files/9540999/vivecraft-0.0.10-fabric.zip)

**Comment by jamac-dumas** [comment]
Okay, I tested this in both singleplayer and on my server, and there were no crashes or unusual behavior. I tested other turtle functions as well and everything worked fine.

Thanks for the fix!
