### ISSUE TITLE
Particle Rain causes crash, when it rains

### ISSUE THREAD

**Issue by fayer3** [ferriarnus/VivecraftForge#43]
crash report:
https://cdn.discordapp.com/attachments/1016839220129710181/1018204205833519175/crash-2022-09-10_17.57.03-client.txt

**Comment by ferriarnus** [comment]
Hmm, it mentions `ClientTickEvents` from the fabric api. Maybe just a missing event?

**Comment by fayer3** [comment]
it could just be that the mod is incompatible with 1.18.2, I'm waiting on response from the reported, to confirm if it worked there for them.

**Comment by fayer3** [comment]
not an issue by us, it's just incompatible with 1.18.2 see here, also has a link to a fork that works
https://github.com/PigCart/particle-rain/issues/15
