### ISSUE TITLE
Enhancement: Change Player Model Size (Possibly Pehkui Integration?)

### ISSUE THREAD

**Issue by crowmaticOrb** [ferriarnus/VivecraftForge#46]
Add the ability to change player model size to under the normal height (maybe over by 1 block or so), to allow Pehkui size changes to be accurately represented.

**Comment by ferriarnus** [comment]
Pehkui is definitly a mod we will look into (since immersive portals also uses it). But for now, we are looking into some other things.

**Comment by ghost** [comment]
pehkui works for the player's model, but the camera doesn't match the model's height.
