### ISSUE TITLE
[Iris] Texture of first-person "on fire" render is broken

### ISSUE THREAD

**Issue by xanthousm** [ferriarnus/VivecraftForge#48]
Just a small Iris compatibility bug, where the "on fire" geometry around the player is a rectangle of green noise instead of the animated fire block texture. My guess is the "ModelBakery.FIRE_1.sprite();" in renderFireInFirstPerson() of GameRendererVRMixin.java needs to be changed to work with Iris?

**Comment by fayer3** [comment]
it works fine for me, are you using shaders or something?

**Comment by fayer3** [comment]
shaders are unsupported right now, but I noticed that fire was green with bsl

**Comment by xanthousm** [comment]
Ah, yes this bug only occurs when a shader is enabled (specifically complementary v4 or reimagined). I just thought to report it since it doesn't seem to be related to the other current issues with shaders and might be overlooked

**Comment by fayer3** [comment]
it's likely just the shader we use for rendering, being incompatible with shaders

**Comment by ferriarnus** [comment]
Thanks for the comment we are looking into shaders, but this does sound like something else than the current issue. We will first see if we can get shaders to work, than we will verify this is solved or not.

**Comment by xanthousm** [comment]
No worries, there are definitely more important bugs to focus on. And fayer3 was right, I just changed the shader used for the fire from getPositionColorTexShader to getPositionTexColorShader (which is used in other places) and its fixed. 
![firefixed](https://user-images.githubusercontent.com/70198941/189797131-f0394972-efdc-4e72-837b-53233166e7ec.png)
