### ISSUE TITLE
Modded SteamVR binds don't work (DiggusMaximus, & FTBUltimine - compatibility)

### ISSUE THREAD

**Issue by ogpw** [ferriarnus/VivecraftForge#59]
I tried to use both DiggusMaximus and then FTBUltimine, but I couldn't get either to work. I set the right grip of my Quest 2 to work as the modded function for each mod "Excavate" for DiggusMaximus and "FTBUltimine" for, you guessed it, FTBUltimine. However, neither appear to work. It doesn't work when using the standard Button mode or Toggle Button mode on the SteamVR controls config.
Both controls have to be held down for them to activate and their function to work (vein-mining).

**Comment by fayer3** [comment]
thanks, is already know, will be fixed in the next release

**Comment by ogpw** [comment]
Thank you for the quick response. I look forward to the next release!
