### ISSUE TITLE
[Forge] the game is not displayed in my Rift S (might do the same for the Quest series)

### ISSUE THREAD

**Issue by Nathan22211** [ferriarnus/VivecraftForge#73]
It'll function normally on the monitor, but it just says waiting in SteamVR even after the game is fully loaded.

Vivecraft: 0.0.12
Forge 40.1.84
on 1.18.2

**Comment by hammy275** [comment]
It works fine on my Quest 2. Do you have both SteamVR and the Oculus software installed? If so, you may want to try launching SteamVR manually before launching the game.

**Comment by Nathan22211** [comment]
I did launch steam VR first, and do first-time setup, and I still get the same issue. Are you sure you tried forge and not fabric?

**Comment by hammy275** [comment]
I'm not sure what the issue is then, tbh. And it works fine for me for both Forge and Fabric. Does it work fine for you in Fabric but not Forge, or does it not work in both of them?

**Comment by fayer3** [comment]
check the FAQ, the game is probably running on your integrated gpu
http://www.vivecraft.org/faq/#gpu

**Comment by fayer3** [comment]
or you connected the rift to your motherboard, instead your GPU

**Comment by Nathan22211** [comment]
@fayer3 it's not, my PC doesn't have a IGPU, it's a X model AMD. I can see the oculus home in the headset and steamVR home but nothing in game comes through other than it saying that Javaw is waiting or it's up next

**Comment by fayer3** [comment]
what is a X model AMD?

**Comment by Nathan22211** [comment]
@fayer3 the X model AMD cpu's don't have a IGPU

**Comment by fayer3** [comment]
and what is your GPU?

**Comment by Nathan22211** [comment]
Rx 5600 XT

**Comment by fayer3** [comment]
can you post a latest.log?

**Comment by Nathan22211** [comment]
Probably not, looking at the latest, no new ones were created when I launched the curse instance with Vivecraft. Cus the latest I made before I used vivecraft

**Comment by fayer3** [comment]
there should always be a latest log, maybe you are looking in the wrong place

**Comment by Nathan22211** [comment]
it's not being generated in my instance's log folder that's fore sure? the last one in there is from this morning

**Comment by fayer3** [comment]
can you get the launcher_log then? it's in Install folder beside the Instances one.

**Comment by fayer3** [comment]
get it after you launched vivecraft

**Comment by fayer3** [comment]
closing  this, because of no response, if you still have this issue, make a new one with the log, or come to our discord for support
