### ISSUE TITLE
Not Enough Animations + First Person Model compatibility 

### ISSUE THREAD

**Issue by Mister-16** [ferriarnus/VivecraftForge#76]
Mods:
Not Enough Animations  - version 1.6.2-1.19 - Fabric
https://modrinth.com/mod/not-enough-animations
First Person Model - version 2.2.1-1.18 - Fabric
https://modrinth.com/mod/first-person-model

Description:
Game loads as normal. loading up a world or joining a server, though, renders a insanely huge model of your player skin above you, width of the feet alone is like 6 blocks. feet also clip into top of actual VR player's head. when you walk around, the huge player skin walks too, so you can see the chest and arms, and the arms actually are rendering correctly, same as vivecraft arms. tried tweaking offset and hand settings but didn't work. 

would love to see this get added as a compatibility!

**Comment by wyldcrd** [comment]
Quick question, have you tried the mods individually inside vr?

**Comment by fayer3** [comment]
First Person Model needs Not Enough Animations to work afaik

**Comment by Mister-16** [comment]
> First Person Model needs Not Enough Animations to work afaik

Correct.

**Comment by wyldcrd** [comment]
Can you use the world scale slider to scale yourself to the size of the “titan” version of yourself or does that rescale the buggy copy too? (Is world scale not in this version of vivecraft?)

**Comment by Mister-16** [comment]
Ok i have no clue what happened, I booted up the game again and the it seems the first person model didn't render at all this time. Not correctly where my body should be, and not the titan either. Here's my latest log/modlist [latest.log](https://github.com/ferriarnus/VivecraftMod/files/10097069/latest.log) if it helps.

**Comment by wyldcrd** [comment]
Would removing performance mods and enhancement mods except First Person Models and NEA and any required other mods help?

And once I get the time I will test FPM and NEA

**Comment by wyldcrd** [comment]
And reading through your latest.log I haven’t seen anything to do with FPM or NEA

Edit: found something
`[15:05:25] [Render thread/WARN]: Discarding @Unique public method getAnimatedSkin in firstperson.mixins.json:DonorAbstractClientPlayerMixin from mod firstperson because it already exists in net.minecraft.class_742
[15:05:25] [Render thread/WARN]: Discarding @Unique public method getAnimatedSkin in notenoughanimations.mixins.json:DonorAbstractClientPlayerMixin from mod notenoughanimations because it already exists in net.minecraft.class_742
[15:05:25] [Render thread/WARN]: Discarding @Unique public method getAnimatedSkin in 3dskinlayers.mixins.json:DonorAbstractClientPlayerMixin from mod skinlayers because it already exists in net.minecraft.class_742
[15:05:25] [Render thread/WARN]: Discarding @Unique public method getAnimatedSkin in waveycapes.mixins.json:DonorAbstractClientPlayerMixin from mod waveycapes because it already exists in net.minecraft.class_742 `

**Comment by Mister-16** [comment]
oh ok, I can try without anything except vivecraft and fpm + nea and see how that goes then

**Comment by wyldcrd** [comment]
Well it would add a full body but you would need to add legs that follow your irl legs along with a body that follows yours if people really needed FBT in a block game

**Comment by Mister-16** [comment]
but without a slidemill or something similar the legs would just stay still. various games have a rendered lower (and upper, to an entent) body that responds to controller inputs, not fbt

**Comment by wyldcrd** [comment]
Or natural locomotion instead of a slidemill

**Comment by Mister-16** [comment]
yeah, that's true. never use it so forgot it exists lol

**Comment by wyldcrd** [comment]
Or the weird version where you push forward on the thumb stick and walk with your arms in locomotion settings

**Comment by Mister-16** [comment]
lol yeah, that one is really weird. I'll be testing that later today, anything else you want me to test besides the whole First Person Models and NEA only with vivecraft?

**Comment by wyldcrd** [comment]
Not anything else I can think of.

**Comment by wyldcrd** [comment]
Because with a ton of other mods you have a ton of other reasons for crashes so you want to limit variables when testing.

If you can get the game to crash with only the 2 mods finding the issue will be easier

**Comment by Mister-16** [comment]
game doesnt crash, loads up like normal. the titan sized player never appears, and I can confirm the mod is there.

**Comment by Mister-16** [comment]
ok nevermind, got it to work. had to delete the configs for NEA and FPM. Here's some screenshots. I tried world scaling, but it didn't scale the titan player at all.
![2022-11-29_17 14 33-min](https://user-images.githubusercontent.com/83727882/204669875-03d18090-7303-482d-bf6f-dc92c6f35d54.png)
![2022-11-29_17 14 44-min](https://user-images.githubusercontent.com/83727882/204669876-caac4a04-21a3-46ba-98bb-bbce87361835.png)
![2022-11-29_17 14 51-min](https://user-images.githubusercontent.com/83727882/204669878-fbda31b6-edb1-411f-8d22-889869928903.png)

**Comment by wyldcrd** [comment]
Have you made an issue on the fpm GitHub?

also does better animations work with vivecraft fine?

**Comment by Mister-16** [comment]
i talked with the dev and he said he intentionally didn't add support for vivecraft, due to it using optifine and forge. I told him abt vivecraft moving to fabric without optifine and he was surprised but said that compatibility was a definite possibility and he'd look into it. said that he has a few other projects to attend to first though. I've never tested better animations, I can tmr (at work rn)

**Comment by EsserGaming** [comment]
Let's go?? First person model in VR???

**Comment by fayer3** [comment]
just the rendering is fixed, the model itself is still just the regular model, so if you duck, you will clip into the body

**Comment by EsserGaming** [comment]
> just the rendering is fixed, the model itself is still just the regular model, so if you duck, you will clip into the body

Good to know, I know that you guys wanted to get FBT into vivecraft. Which I'm assuming this is a step closer to that.

**Comment by fayer3** [comment]
has nothing to do with that fix, this just fixes calling the render of the player outside the levelrendering

**Comment by fayer3** [comment]
rendering the player should have always worked, just that that mod called it at a weird place

**Comment by EsserGaming** [comment]
Ah, alright
