### ISSUE TITLE
Couldn't get the game view in steamVR

### ISSUE THREAD

**Issue by VoxelFloof** [ferriarnus/VivecraftForge#77]
if I launch it outside of steamVR
I'm stuck on this forever
![image](https://user-images.githubusercontent.com/94568504/205424672-a392e437-e589-4222-a028-0760c20542bd.png)
well I can technically still able to play the game thought, I juat have to use OVR toolkit to play

& if try to launch it in steamVR, well... it will never launch

**Comment by fayer3** [comment]
see: http://www.vivecraft.org/faq/#gpu
you were also told that in discord
