### ISSUE TITLE
glitchy view of game

### ISSUE THREAD

**Issue by ghost** [ferriarnus/VivecraftForge#86]
everything on bottom left of screen unplayable sadly please fix or give someway to workaround it

**Comment by fayer3** [comment]
afaik, that is caused by essentials

**Comment by ferriarnus** [comment]
Can you include an image? Also the mod version and other mods installed.

**Comment by ferriarnus** [comment]
> afaik, that is caused by essentials

Oh right, in that case, not our fault and known by essentials.

**Comment by ghost** [comment]
oh ok, is there any workaround?

**Comment by ghost** [comment]
also i will post screenshot soon

**Comment by fayer3** [comment]
it should only affect the menu, if you get in game it should be fine

**Comment by ghost** [comment]
omg thx

**Comment by ghost** [comment]
alright so everything that is not a liquid and hands or gui is fine but uhhh the actual world is on the bottom left

**Comment by fayer3** [comment]
then send a log please

**Comment by ghost** [comment]
alright the log that is currently printing (launcher log output) or a certain file?

**Comment by fayer3** [comment]
latest.log should be fine

**Comment by ghost** [comment]
alright

**Comment by ghost** [comment]
[latest.log](https://github.com/ferriarnus/VivecraftMod/files/10200546/latest.log)

**Comment by ghost** [comment]
![2022-12-10_17 06 15](https://user-images.githubusercontent.com/84929796/206866952-eaacb30d-7556-4918-85e9-fd8e5a3bfc64.png)

**Comment by fayer3** [comment]
hm, since that is just essentials, not much we can do

**Comment by ghost** [comment]
oki also if this helps, i put it in fullscreen and it changed, mabye its a resolution scaling thingy issue or something lol idk
![2022-12-10_17 14 53](https://user-images.githubusercontent.com/84929796/206867095-60fa3cfa-bfc6-4960-996a-02abdbf8c531.png)

**Comment by ghost** [comment]
odd that everything is stretched though

**Comment by ghost** [comment]
so is it an issue with essential then or Vivecraft, as the og vivecraft crashes when using it (even though im using the forge version for both)

**Comment by wyldcrd** [comment]
It’s on both essential’s side and ours. Essential has performance features that can be disabled I believe, so maybe try that next? To access the settings it’s /essential, and if that doesn’t work try the essential config .txt

**Comment by ghost** [comment]
alright thx

**Comment by ghost** [comment]
sadly that did not work

**Comment by wyldcrd** [comment]
🤷‍♂️ not much that fayer or ferri can do about it then unless the essential team wants to work with them

**Comment by ghost** [comment]
oki dokie, should i close this issue now?

**Comment by wyldcrd** [comment]
Close as not planned unless fayer3 or ferri say otherwise
