### ISSUE TITLE
Contextual Interact not working

### ISSUE THREAD

**Issue by ElReptil** [ferriarnus/VivecraftForge#87]
Hi,

I can't seem to get the Contextual Interact (i.e. interacting with blocks and entities that my hands are touching) to work; not sure if it's been (re-)implemented yet. I'm currently using Fabric 1.19.2 with vivecraft-1.19.2-0.0.13.

I have the Contextual Interact action bound to my grips (I'm on an Index), but it doesn't do anything. I've tried gripping while touching doors, chests, villagers and trapdoors, all of which used to work in Forge 1.16.5.

**Comment by fayer3** [comment]
can you make sure that it doesn't roomscale crouch

**Comment by ElReptil** [comment]
Definitely not crouching (there's no sneak icon next to the hotbar). Disabling roomscale crouching also doesn't change anything.

I just noticed that I also don't have the little outline that used to appear around interactable blocks when touching them.

**Comment by fayer3** [comment]
can confirm it not working

**Comment by fayer3** [comment]
hm, it's working in dev, must be something with the mappings maybe. will look at it later

**Comment by ElReptil** [comment]
Thanks for looking into it.
