### ISSUE TITLE
[FABRIC] Compatibility issue with the mod Hephaestus (Tinkers Construct)

### ISSUE THREAD

**Issue by Niphoria** [ferriarnus/VivecraftForge#88]
When having Hephaestus loaded while in VR it plumits your FPS down to about 20. Checking with Spark reveals that 50-60% of the performance goes towards openGL errors. I sadly dont know how to print these out so ill happily provide more information if someone tells me how to - checking the logs revealed nothing. Playing NON-VR does not have this issue - it only happens while playing VR. 

Minecraft Version: 1.18.2
Fabric Version: 0.14.11
Fabric API Version: 0.67.0
Vivecraft Version: 0.0.13
Hephaestus Version: 3.5.2.155
(Tested with just these 3 mods loaded - Fabric API, Vivecraft, Hephaestus)

![Capturaaaae](https://user-images.githubusercontent.com/55203946/207890803-cb32ff8b-32a2-4f69-bb3b-19b94c1a738e.PNG)

**Comment by fayer3** [comment]
likely the same issues as #71 
one of the dependencies of Hephaestus includes Satin
you can try disabling the `eye stencil` in VR Settings -> Stereo Rendering

**Comment by Niphoria** [comment]
Thank you - that fixes the issue!
