### ISSUE TITLE
Unable to enter VR mode

### ISSUE THREAD

**Issue by Slooshie1** [ferriarnus/VivecraftForge#98]
Every time I launch the game it starts in NONVR mode as seen in the window title and it tells me to restart my game. This happens on only quilt and vivecraft, this particular test was recorded on my modpack

https://user-images.githubusercontent.com/90230538/210890715-ee1dfab2-6d7f-45fb-9a5c-711e574afc96.mp4

**Comment by fayer3** [comment]
issue with quilt 0.18. there is an alpha with it already fixed in the vivecraft discords
